version: "3.0"
services:
  db:
    container_name: postgres-app-db
    image: library/postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb

  rabbitmq:
    container_name: rabbitmq
    image: library/rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      USER: admin
      PASSWORD: admin
      NAME: rabbitmq
